baseURL = "https://jofragotre.github.io/Website/"
title = "Tremoço"
theme = "congo"
languageCode = "en"
defaultContentLanguage = "en"
relativeURLs = false
canonifyURLs = true

[taxonomies]
  tag = "tags"

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true