[homepage]
  layout = "profile" 
  showRecent = false

[assets]
  favicon = "favicon.ico"

[article]
  showTableOfContents = true
  showDate = false
  showAuthor = false
  showReadingTime = false

[toc]
  enabled = true

[footer]
  showAppearanceSwitcher = true

[list]
  showSummary = true